### ISSUE TITLE
Quickstart crashes upon installing the client

### ISSUE THREAD

**Issue by Braqzen** [axiom-crypto/axiom-docs#17]
In the [following section](https://github.com/axiom-crypto/axiom-docs/blob/main/docs/docs/introduction/quickstart.md#quickstart) we are told to run a single command to set up a project.

Upon running the command the project crashes. The command requires prerequisite steps before running the command and thus the docs ought to be updated to reflect any additional steps.

![1](https://github.com/axiom-crypto/axiom-docs/assets/103777923/0e6cdd6a-736c-4144-b020-e59f879e6001)

**Comment by ytham** [comment]
@Braqzen thanks for the report! there was unfortunately an issue in the version detection for create-axiom-client. I've pushed a fix, but you'll need to clear your npx cache and run the command again:

```
npx clear-npx-cache
npx create-axiom-client
```

Please let me know if that fixes it for you.
